export const ALL_EVENTS_REQUEST = 'ALL_EVENTS_REQUEST'
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'
export const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'

export const NEW_EVENT_REQUEST = 'NEW_EVENT_REQUEST'
export const NEW_EVENT_SUCCESS = 'NEW_EVENT_SUCCESS'
export const NEW_EVENT_RESET = 'NEW_EVENT_RESET'
export const NEW_EVENT_FAIL = 'NEW_EVENT_FAIL'

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_RESET = 'DELETE_EVENT_RESET'
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL'

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_RESET = 'UPDATE_EVENT_RESET'
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const NEW_USER_REQUEST = 'NEW_USER_REQUEST'
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS'
export const NEW_USER_RESET = 'NEW_USER_RESET'
export const NEW_USER_FAIL = 'NEW_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'